### ISSUE TITLE
How did you use a linear layer in Design D?

### ISSUE THREAD

**Issue by tomo120717** [LostXine/crossway_diffusion#3]
Thank you for your work.

In your paper, you compaired Design D with Design A, B, and C. I want to conduct Design D program, but we cannot find it from your codes. So, I want to check the result of Design D on my own.

In Design D, the shape of it is [batch, 247]. On the other hand, in Design A, the shape of it is [batch, 2048]. The shape of Type D and A is different. In your paper, about Design D, "A linear layer is also applied to project h_t to the target dimension C/4 in the channel axis." I think this sentence means that you appkied Linear(247, 2048) to h_t. Is it correct?

Thanks.

**Comment by LostXine** [comment]
Hi @tomo120717 ,

Thanks for your interest! 

Your understanding is correct and I've updated the corresponding code. Sorry, I was busy with another project back then and totally forgot this. Also, I found a bug here that fails to initialize type b or c, this has been fixed as well.
https://github.com/LostXine/crossway_diffusion/blob/8c2ef93edd69a0c3066b5959ef4ee605a2b8dc4d/diffusion_policy/policy/crossway_diffusion_unet_hybrid_image_policy.py#L144-L149

Please let me know if you have any other questions as well.

Thanks,

**Comment by tomo120717** [comment]
Hi @LostXine ,

Thank you for your reply and updating your code! I understand your experiment and code.

I have more question about comment of your code.

Like this part, in your code, shape is formed from 64 x 2048 to (64 x 2) x 128 x 2 x 2. The number of parameter is needed to keep, but this is not done (64 x 2048) != (64 x 1024). Is this correct?
https://github.com/LostXine/crossway_diffusion/blob/883a310c1f38cb74a159056a14a236dafc957275/diffusion_policy/model/diffusion/conditional_unet1d.py#L412C1-L416C41

In my opinion, in other class of thie file (ConditionalUnet1DwDecTypeC and ConditionalUnet1DwDecTypeB), the shapes are incorrect, too. I reccomend you to check them.

Thanks,

**Comment by LostXine** [comment]
Hi @tomo120717 ,

Thanks for pointing it out, the correct size should be (64 x 2) x **256** x 2 x 2. I've updated the comments in all types, sorry for the confusion.

Thanks for your understanding.

Best,

**Comment by tomo120717** [comment]
Hi, @LostXine ,

Thank you very much! I appreciate your cooperation.

**Comment by LostXine** [comment]
@tomo120717 Thank you so much for your effort! I'll close this issue as everything looks good now. Please don't hesitate to start a new issue or reopen this one if you find anything unclear.

Best,
