### ISSUE TITLE
Inquiry on Results Discrepancies in Table II

### ISSUE THREAD

**Issue by NUS-WWS** [LostXine/crossway_diffusion#7]
Dear authors:
I would like to express my appreciation for your significant contributions. The methodologies presented in your work are both innovative and inspiring.

However, while analyzing your results, particularly those presented in Table 2, I noticed a significant difference when compared to the baseline results presented in **Diffusion Policy**. Take Push-T task as an example, the mean score is **0.819** as shown in your paper, while it can achieve nearly 0.90 in the original DP paper.

Could you please provide some insights into the possible reasons for these discrepancies? Were there any variations in the experimental setup, datasets used, or evaluation metrics that might account for these differences?

Thank you for your time and consideration.
![屏幕截图 2024-08-06 09:51:27](https://github.com/user-attachments/assets/e61e2f52-df08-4f28-89dc-452f07a96c0d)

**Comment by LostXine** [comment]
Hi @NUS-WWS ,

Thanks for your interest in our work. 
In short, we are using a different evaluation metric compared to the original DP paper as described in our paper. 

DP presents success rates with different checkpoint selection methods in the format
of (max performance) / (average of last 10 checkpoints), with each averaged across 3 training seeds and 50 different environment initial conditions (150 in total). All the models are trained for 3000 epochs and the last checkpoints were sampled every 50 epochs. In addition, [this bug](https://github.com/real-stanford/diffusion_policy/issues/6) may introduce some errors as well.

In comparison, our paper reports the scores averaged across 3 training seeds and 1000 different environment initial conditions (3000 in total). All the methods in our paper are trained for 500 epochs.

Hope it helps.

Best,

Xiang

**Comment by NUS-WWS** [comment]
Thanks for your prompt response! I understand. Have a nice day~
